export const BASE_URL = "http://localhost:4056"
export const SIGNUP = BASE_URL + "/api/register"
export const SIGNIN = BASE_URL + "/api/login"
export const RESET_EMAIL = BASE_URL + "/api/senduserpasswordresetemail"
export const FORGOT_PASSWORD = BASE_URL + 
"/api/userpasswordreset"
export const USER_LIST = BASE_URL + "/admin/userlist"
export const DELETE_USER = BASE_URL + "/admin/managuserstatus"
export const USER_STATUS = BASE_URL + "/admin/managuserstatus"
export const CHANGE_PASSWORD = BASE_URL+"/user/changepassword"
export const EDIT_PROFILE = BASE_URL + "/user/editprofile"
export const USER_POST = BASE_URL + "/user/postlist"
export const ADD_POST = BASE_URL + "/user/post"
export const ADMIN_USER_POST = BASE_URL + "/admin/posts"
export const SINGLE_USER = BASE_URL + "/admin/user"